name: Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: docker
    steps:
      - uses: https://code.forgejo.org/actions/checkout@v2
        name: Checkout Files

      - name: Install pnpm
        uses: pnpm/action-setup@v5
        with:
          version: 10

      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build site
        run: pnpm run build

      - name: Compress Files
        uses: stefh/ghaction-CompressFiles@v2
        with:
          path: dist/
          extensions: '.js,.css,.html'
          tools: 'brotli,gzip'

      - name: Deploy with rsync
        if: github.event_name == 'push'
        uses: https://github.com/burnett01/rsync-deployments@v8
        with:
          switches: -avzr --delete
          path: dist/
          remote_path: ${{ secrets.RSYNC_REMOTE_PATH }}
          remote_host: ${{ secrets.RSYNC_REMOTE_HOST }}
          remote_port: ${{ secrets.RSYNC_REMOTE_PORT }}
          remote_user: ${{ secrets.RSYNC_REMOTE_USER }}
          remote_key: ${{ secrets.RSYNC_REMOTE_KEY }}