name: Deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:  
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: docker

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: https://code.forgejo.org/actions/checkout@v2
        name: Checkout Files

      # - name: Install pnpm
      #   uses: pnpm/action-setup@v5
      #   with:
      #     version: 10

      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          # cache: 'pnpm'

      - name: Install dependencies
        run: npm install
      
      - name: Build site
        run: npm run build

      - name: Deploy with rsync
        uses: https://github.com/burnett01/rsync-deployments@v8.0.4
        with:
          switches: -avzr --delete
          path: dist/
          remote_path: ${{ secrets.RSYNC_REMOTE_PATH }}
          remote_host: ${{ secrets.RSYNC_REMOTE_HOST }}
          remote_port: ${{ secrets.RSYNC_REMOTE_PORT }}
          remote_user: ${{ secrets.RSYNC_REMOTE_USER }}
          remote_key:  ${{ secrets.RSYNC_REMOTE_KEY  }}
